### ISSUE TITLE
TODO - 1 

### ISSUE THREAD

**Issue by xxidbr9** [xxidbr9/kontan-app#1]
- [x] Add Splashscreen
- [x] Install SQLite 2 for main DB
- [x] Add Base UI
- [x] Fix naming architecture
- [x] Use Hermes as the default engine
- [x] Add i18n for checking default language
